@startuml
|主流程|
start
:种类繁多数量巨大的日志;
:抽取共性;
-[#blue]->获得规律;

|#AntiqueWhite|获得规律流程|
:获得文件;
:打开文件;
:读取日志结构;

|延迟到子类的实现|

-[#red,dotted]->处理单行日志;
:执行主流程;
:钩子函数:beforeProcessOneFile();
:扩展点...;
:钩子函数afterProcessOneFile();
-[#red,dotted]->

|获得规律流程|
:清理工作;

|主流程|
stop

@enduml